// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhB3bQrbaplaWuU7YXA-xV-wx4VNMlGms',
    appId: '1:817932222161:web:70e76bb089329a97554ff0',
    messagingSenderId: '817932222161',
    projectId: 'app-libros-55494',
    authDomain: 'app-libros-55494.firebaseapp.com',
    storageBucket: 'app-libros-55494.appspot.com',
    measurementId: 'G-CNQ6381SNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmN-SK1UiSpeGv8v8Lv0-4oWkA7VG84g',
    appId: '1:817932222161:android:bbf44f42e9d44383554ff0',
    messagingSenderId: '817932222161',
    projectId: 'app-libros-55494',
    storageBucket: 'app-libros-55494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tL5Satd9p7ZcbOkrvgmd-YQWGZ9XSII',
    appId: '1:817932222161:ios:1a07237102b3df50554ff0',
    messagingSenderId: '817932222161',
    projectId: 'app-libros-55494',
    storageBucket: 'app-libros-55494.appspot.com',
    iosClientId: '817932222161-ak0psj9arakgbc04r8f9qgcu61knlhad.apps.googleusercontent.com',
    iosBundleId: 'com.davis.appLibros',
  );
}
